# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    redmine_api_client:
        class: Redmine\Client
        arguments: ["%redmine_base_url%", "%redmine_api_key%"]
    redmine_manager:
        class: AppBundle\Services\RedmineManager
        arguments: ["@redmine_api_client", "%pagination_limit%"]
    time_entry_manager:
        class: AppBundle\Services\TimeEntryManager
        arguments: ["@redmine_manager", "@form.factory", "@router"]
    comment_manager:
        class: AppBundle\Services\CommentManager
        arguments: ["@redmine_manager", "@form.factory", "@router", "@doctrine"]